"""add payroll, batch_workers, commission_rates

Revision ID: 24a5306bcf32
Revises: 6d71ddb7f071
Create Date: 2026-04-10 06:10:00.801799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24a5306bcf32'
down_revision: Union[str, Sequence[str], None] = '6d71ddb7f071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

employmenttype=sa.Enum('SALARY', 'COMMISSION', name='employment_type')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdivisions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subdivisions_is_active'), 'subdivisions', ['is_active'], unique=False)
    op.create_table('payrolls',
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PAID', name='payrollstatus'), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payrolls_is_active'), 'payrolls', ['is_active'], unique=False)
    op.create_table('payslips',
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_id'], ['payrolls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_is_active'), 'payslips', ['is_active'], unique=False)
    op.create_index(op.f('ix_payslips_payroll_id'), 'payslips', ['payroll_id'], unique=False)
    op.create_table('product_commission_rates',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    postgresql.ExcludeConstraint((sa.column('product_id'), '='), (sa.text("daterange(effective_from, effective_to, '[]')"), '&&'), using='gist', name='ck_no_overlapping_commission_rates'),
    sa.CheckConstraint('rate_per_unit > 0', name='ck_positive_commission_rate'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_commission_rates_is_active'), 'product_commission_rates', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_commission_rates_product_id'), 'product_commission_rates', ['product_id'], unique=False)
    op.create_table('subdivision_members',
    sa.Column('subdivision_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subdivision_id'], ['subdivisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdivision_id', 'employee_id', name='uq_subdivision_member')
    )
    op.create_index(op.f('ix_subdivision_members_employee_id'), 'subdivision_members', ['employee_id'], unique=False)
    op.create_index(op.f('ix_subdivision_members_is_active'), 'subdivision_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_subdivision_members_subdivision_id'), 'subdivision_members', ['subdivision_id'], unique=False)
    op.create_table('batch_workers',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'employee_id', name='uq_batch_worker')
    )
    op.create_index(op.f('ix_batch_workers_batch_id'), 'batch_workers', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_workers_employee_id'), 'batch_workers', ['employee_id'], unique=False)
    op.create_index(op.f('ix_batch_workers_is_active'), 'batch_workers', ['is_active'], unique=False)
    op.create_table('payslip_commission_lines',
    sa.Column('payslip_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('subdivision_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_quantity', sa.Integer(), nullable=False),
    sa.Column('present_count', sa.Integer(), nullable=False),
    sa.Column('quantity_share', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subdivision_id'], ['subdivisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_commission_lines_is_active'), 'payslip_commission_lines', ['is_active'], unique=False)
    op.create_index(op.f('ix_payslip_commission_lines_payslip_id'), 'payslip_commission_lines', ['payslip_id'], unique=False)
    op.add_column('batches', sa.Column('subdivision_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_batches_subdivision_id'), 'batches', ['subdivision_id'], unique=False)
    op.create_foreign_key(None, 'batches', 'subdivisions', ['subdivision_id'], ['id'], ondelete='RESTRICT')
    employmenttype.create(op.get_bind(), checkfirst=True)
    op.add_column('employees', sa.Column('employment_type', employmenttype, nullable=False))
    op.alter_column('employees', 'base_salary',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'base_salary',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_column('employees', 'employment_type')
    employmenttype.drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_index(op.f('ix_batches_subdivision_id'), table_name='batches')
    op.drop_column('batches', 'subdivision_id')
    op.drop_index(op.f('ix_payslip_commission_lines_payslip_id'), table_name='payslip_commission_lines')
    op.drop_index(op.f('ix_payslip_commission_lines_is_active'), table_name='payslip_commission_lines')
    op.drop_table('payslip_commission_lines')
    op.drop_index(op.f('ix_batch_workers_is_active'), table_name='batch_workers')
    op.drop_index(op.f('ix_batch_workers_employee_id'), table_name='batch_workers')
    op.drop_index(op.f('ix_batch_workers_batch_id'), table_name='batch_workers')
    op.drop_table('batch_workers')
    op.drop_index(op.f('ix_subdivision_members_subdivision_id'), table_name='subdivision_members')
    op.drop_index(op.f('ix_subdivision_members_is_active'), table_name='subdivision_members')
    op.drop_index(op.f('ix_subdivision_members_employee_id'), table_name='subdivision_members')
    op.drop_table('subdivision_members')
    op.drop_index(op.f('ix_product_commission_rates_product_id'), table_name='product_commission_rates')
    op.drop_index(op.f('ix_product_commission_rates_is_active'), table_name='product_commission_rates')
    op.drop_table('product_commission_rates')
    op.drop_index(op.f('ix_payslips_payroll_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_is_active'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_payrolls_is_active'), table_name='payrolls')
    op.drop_table('payrolls')
    op.drop_index(op.f('ix_subdivisions_is_active'), table_name='subdivisions')
    op.drop_table('subdivisions')
    # ### end Alembic commands ###
