"""add constraint to product prices

Revision ID: e98f035a5349
Revises: b0520e1890cd
Create Date: 2026-04-07 00:05:50.014777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e98f035a5349"
down_revision: Union[str, Sequence[str], None] = "b0520e1890cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute("""
    ALTER TABLE product_prices
    ADD CONSTRAINT ck_no_overlapping_product_prices
    EXCLUDE USING gist (
        product_id WITH =,
        daterange(effective_from, effective_to, '[]') WITH &&
    )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_no_overlapping_product_prices", "product_prices")
    op.execute("DROP EXTENSION IF EXISTS btree_gist")
    # ### end Alembic commands ###
