"""add note to inventory_transactions

Revision ID: ff7fa1d72be6
Revises: 24a5306bcf32
Create Date: 2026-04-10 07:02:19.147648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7fa1d72be6'
down_revision: Union[str, Sequence[str], None] = '24a5306bcf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_transactions', sa.Column('note', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_transactions', 'note')
    # ### end Alembic commands ###
