"""batch is_confirmed

Revision ID: b26764097954
Revises: db961bf5b36e
Create Date: 2026-04-01 15:18:39.298809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26764097954'
down_revision: Union[str, Sequence[str], None] = 'db961bf5b36e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('is_confirmed', sa.Boolean(), server_default=sa.text("'FALSE'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'is_confirmed')
    # ### end Alembic commands ###
