name: Deploy Inven
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull the latest code
        run: |
          cd ~/projects/inven/
          git pull

      - name: Deploy
        run: |
          cd ~/projects/inven/
          docker compose up -d --build
